"""Track-A schema-drift gate (ADVISORY CI signal).

The repo ships committed JSON-Schema artifacts under ``docs/contracts/schemas/``
(one ``<name>.v1.json`` per pydantic model, plus ``manifest.json``). These are
generated from the pydantic models in ``dietary_mcp.contracts`` via
``generate_contract_artifacts``.

This is a regenerate-and-compare (``check_contract_drift``) gate: it regenerates
every schema (and the schema manifest) IN MEMORY from the current pydantic
models and asserts the result is BYTE-IDENTICAL to the committed file. It never
writes to the working tree (unlike ``tests/test_contracts.py``, which is marked
slow/contract and regenerates artifacts on disk before validating examples).

PROOF IT BITES: change a pydantic model field (or hand-edit a committed schema)
without regenerating -> the regenerated bytes diverge from committed -> this test
FAILS with the drifted schema name attributed. Regenerate
(``dietary-mcp-generate-artifacts`` / ``uv run dietary-mcp-validate
--generate-artifacts``) and commit -> green.
"""

from __future__ import annotations

import json
from pathlib import Path

from dietary_mcp.contracts import SCHEMA_MODELS, build_contract_manifest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO_ROOT / "docs" / "contracts" / "schemas"


def _expected_schema_text(model: type) -> str:
    # Mirror generate_contract_artifacts exactly: indent=2 + trailing newline.
    return json.dumps(model.model_json_schema(), indent=2) + "\n"


def _expected_manifest_text() -> str:
    return json.dumps(build_contract_manifest(), indent=2) + "\n"


def test_committed_schemas_match_pydantic_regeneration() -> None:
    drifted: list[str] = []
    missing: list[str] = []

    for name, model in sorted(SCHEMA_MODELS.items()):
        path = SCHEMA_DIR / f"{name}.json"
        if not path.exists():
            missing.append(name)
            continue
        if path.read_text() != _expected_schema_text(model):
            drifted.append(name)

    manifest_path = SCHEMA_DIR / "manifest.json"
    manifest_ok = manifest_path.exists() and manifest_path.read_text() == _expected_manifest_text()

    assert not missing, (
        "Committed schema files are missing for these models: "
        f"{missing}. Run `uv run dietary-mcp-validate --generate-artifacts` and commit."
    )
    assert not drifted, (
        "Committed JSON-Schema artifacts have drifted from the pydantic models "
        f"that generate them: {drifted}. Run "
        "`uv run dietary-mcp-validate --generate-artifacts` and commit the "
        "regenerated docs/contracts/schemas/*.json."
    )
    assert manifest_ok, (
        "docs/contracts/schemas/manifest.json has drifted from the schema set. "
        "Run `uv run dietary-mcp-validate --generate-artifacts` and commit."
    )


def test_no_orphan_or_undeclared_committed_schemas() -> None:
    committed = {path.stem for path in SCHEMA_DIR.glob("*.json") if path.name != "manifest.json"}
    declared = set(SCHEMA_MODELS.keys())

    orphans = sorted(committed - declared)
    undeclared = sorted(declared - committed)

    assert not orphans, (
        "Committed schema files have no backing pydantic model (delete or wire up): "
        f"{orphans}."
    )
    assert not undeclared, (
        "Pydantic models declared in SCHEMA_MODELS have no committed schema file "
        f"(regenerate and commit): {undeclared}."
    )
